package gui;

import log.Message;

import javax.swing.JOptionPane;

import log.LogDir;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LYNN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        container_login_jPanel2 = new javax.swing.JPanel();
        psw_jLabel = new javax.swing.JLabel();
        acNo_jLabel = new javax.swing.JLabel();
        accountNumber_login_jTextField = new javax.swing.JTextField();
        login_login_jButton = new javax.swing.JButton();
        welcome_jLabel = new javax.swing.JLabel();
        password_login_jPasswordField = new javax.swing.JPasswordField();
        exit_login_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container_login_jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        container_login_jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        psw_jLabel.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        psw_jLabel.setText("ÃÜ Âë£º");

        acNo_jLabel.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        acNo_jLabel.setText("¿¨ ºÅ£º");

        accountNumber_login_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumber_login_jTextFieldActionPerformed(evt);
            }
        });

        login_login_jButton.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        login_login_jButton.setText("µÇÂ¼");
        login_login_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_login_jButtonActionPerformed(evt);
            }
        });

        welcome_jLabel.setFont(new java.awt.Font("ËÎÌå", 0, 20)); // NOI18N
        welcome_jLabel.setText("»¶ Ó­ Ê¹ ÓÃ ATM Ä£ Äâ Ïµ Í³");

        password_login_jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_login_jPasswordFieldActionPerformed(evt);
            }
        });

        exit_login_jButton.setFont(new java.awt.Font("ËÎÌå", 0, 16)); // NOI18N
        exit_login_jButton.setText("ÍË³ö");
        exit_login_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_login_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout container_login_jPanel2Layout = new javax.swing.GroupLayout(container_login_jPanel2);
        container_login_jPanel2.setLayout(container_login_jPanel2Layout);
        container_login_jPanel2Layout.setHorizontalGroup(
            container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_login_jPanel2Layout.createSequentialGroup()
                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_login_jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(container_login_jPanel2Layout.createSequentialGroup()
                                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(psw_jLabel)
                                    .addComponent(acNo_jLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accountNumber_login_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(password_login_jPasswordField)))
                            .addComponent(welcome_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(container_login_jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(login_login_jButton)
                        .addGap(61, 61, 61)
                        .addComponent(exit_login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        container_login_jPanel2Layout.setVerticalGroup(
            container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container_login_jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountNumber_login_jTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acNo_jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(psw_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(password_login_jPasswordField))
                .addGap(34, 34, 34)
                .addGroup(container_login_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_login_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(exit_login_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container_login_jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container_login_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void accountNumber_login_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void login_login_jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	String accNo = accountNumber_login_jTextField.getText().trim();
    	String psw = String.valueOf(password_login_jPasswordField.getPassword()).trim();
    	System.out.println(psw);
    	
    	if(!accNo.equals("") &&  !psw.equals("")) {
    		Message login_msg = new Message(accNo,psw,0,0,"*");
    	
    		client.sendMSG(login_msg);
    		Message login_ack = client.ReciveMSG();
    	
    		if(login_ack.getOperation() == 0) {
    		
    			new FuncFrame().setVisible(true);
    			this.setVisible(false);
    		
    		}
    		else {
    			JOptionPane.showMessageDialog(getParent(), "µÇÂ¼Ê§°Ü");
    		}
    	}
    	else {
    		JOptionPane.showMessageDialog(getParent(), "ÇëÌîÐ´µÇÂ¼ÐÅÏ¢");
    	}
    	
    	
    	
    	
    }                                                   

    private void password_login_jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void exit_login_jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    	System.exit(0);
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel acNo_jLabel;
    private javax.swing.JTextField accountNumber_login_jTextField;
    private javax.swing.JPanel container_login_jPanel2;
    private javax.swing.JButton exit_login_jButton;
    private javax.swing.JButton login_login_jButton;
    private javax.swing.JPasswordField password_login_jPasswordField;
    private javax.swing.JLabel psw_jLabel;
    private javax.swing.JLabel welcome_jLabel;
    private socket.Client client;
    
    // End of variables declaration                   
}
