package gui;

import java.util.Iterator;

import javax.swing.JOptionPane;

import log.Message;
import log.OptionQueue;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LYNN
 */
public class PaintingGUI extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 70713964107602916L;
	/**
     * Creates new form PaintingGUI
     */
	
    public PaintingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        paint_jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paint_paint_jButton = new javax.swing.JButton();
        cancel_paint_jButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        proof_paint_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paint_jPanel.setBackground(new java.awt.Color(204, 204, 255));
        paint_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("打 印 凭 证");

        paint_paint_jButton.setText("打印");
        paint_paint_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paint_paint_jButtonActionPerformed(evt);
            }
        });

        cancel_paint_jButton.setText("取消");
        cancel_paint_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_paint_jButtonActionPerformed(evt);
            }
        });

        proof_paint_jTextArea.setColumns(20);
        proof_paint_jTextArea.setRows(5);
        jScrollPane1.setViewportView(proof_paint_jTextArea);

        javax.swing.GroupLayout paint_jPanelLayout = new javax.swing.GroupLayout(paint_jPanel);
        paint_jPanel.setLayout(paint_jPanelLayout);
        paint_jPanelLayout.setHorizontalGroup(
            paint_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paint_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(paint_jPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(paint_paint_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_paint_jButton)
                .addGap(72, 72, 72))
            .addGroup(paint_jPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        paint_jPanelLayout.setVerticalGroup(
            paint_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paint_jPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paint_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paint_paint_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_paint_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paint_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paint_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void paint_paint_jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	this.paint_action();
    	
    	JOptionPane.showMessageDialog(this.getContentPane(), "打印成功！");
    }                                                   

    private void cancel_paint_jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    	new FuncFrame().setVisible(true);
    	this.setVisible(false);
    } 
    
    private void paint_action() {
    	bill_text = "";
    	bill_text += Cfg.getBankName()+Cfg.getBranchName()+"欢迎您！\n"+"ATM编号"+Cfg.getAtmsn()+"\n";
    	Iterator<Message> it = User.opq.getOpq().iterator();
    	while(it.hasNext()) {
    		Message msg = it.next();
    		bill_text += msg.displayOnText();
    	}
    	proof_paint_jTextArea.setText(bill_text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancel_paint_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paint_jPanel;
    private javax.swing.JButton paint_paint_jButton;
    private javax.swing.JTextArea proof_paint_jTextArea;
    private String bill_text;
    private OptionQueue haveDone = null;
    // End of variables declaration                   
}

